# Generated by Django 3.1.4 on 2021-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=20, verbose_name='վերնագիր')),
                ('text', models.TextField(verbose_name='տեքստ')),
                ('image', models.ImageField(upload_to='news', verbose_name='նկար')),
            ],
        ),
    ]
