# Generated by Django 3.1.4 on 2021-09-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='titel',
            new_name='title',
        ),
    ]
