# Generated by Django 3.1.4 on 2021-09-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210903_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'նյութ', 'verbose_name_plural': 'նյութեր'},
        ),
    ]
