# Generated by Django 3.1.4 on 2021-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210905_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='հասցե')),
                ('name', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('VKontakte', 'VKontakte'), ('LinkedIn', 'LinkedIn'), ('Odnoklassniki', 'Odnoklassniki')], max_length=15, verbose_name='անուն')),
            ],
        ),
    ]
