# Generated by Django 3.1.4 on 2021-09-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'կաիք', 'verbose_name_plural': 'կաիքեր'},
        ),
    ]
