# Generated by Django 3.1.4 on 2021-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210913_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='անուն')),
                ('image', models.ImageField(upload_to='slide', verbose_name='նկար')),
                ('urls', models.URLField(verbose_name='հասցե')),
            ],
            options={
                'verbose_name': 'սլաիդ',
                'verbose_name_plural': 'սլաիդեր',
            },
        ),
    ]
