# Generated by Django 3.1.4 on 2021-09-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='urls',
            new_name='url',
        ),
    ]
