# Generated by Django 3.1.4 on 2021-09-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210914_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='name',
        ),
    ]
