# Generated by Django 3.1.4 on 2021-09-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_slide_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='url',
        ),
    ]
