# Generated by Django 3.1.4 on 2021-09-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_slide_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='url',
            field=models.URLField(default=1, verbose_name='հասցե'),
            preserve_default=False,
        ),
    ]
