# Generated by Django 3.1.4 on 2021-09-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_slide_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=100, verbose_name='պաշտոն')),
                ('name', models.CharField(max_length=100, verbose_name='անուն')),
            ],
            options={
                'verbose_name': 'հաստիք',
                'verbose_name_plural': 'Հաստիքացուցակ',
            },
        ),
    ]
