# Generated by Django 3.1.4 on 2021-09-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_data_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_contact',
            options={'verbose_name': 'հեռախոսահամար', 'verbose_name_plural': 'կոնտակտաին տվյալներ'},
        ),
    ]
