# Generated by Django 3.1.4 on 2021-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210918_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_contact',
            name='name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('VKontakte', 'VKontakte'), ('LinkedIn', 'LinkedIn'), ('Odnoklassniki', 'Odnoklassniki')], default=1, max_length=20, verbose_name=''),
            preserve_default=False,
        ),
    ]
