# Generated by Django 3.1.4 on 2021-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_data_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_contact',
            name='name',
            field=models.CharField(choices=[('@mail', '@mail'), ('num', 'num')], max_length=20, verbose_name=''),
        ),
    ]
