# Generated by Django 3.1.4 on 2021-09-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210918_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_contact',
            name='gmail',
            field=models.CharField(max_length=12, verbose_name='Gmail'),
        ),
        migrations.AlterField(
            model_name='data_contact',
            name='mail',
            field=models.CharField(max_length=12, verbose_name='@mail'),
        ),
        migrations.AlterField(
            model_name='data_contact',
            name='name',
            field=models.CharField(choices=[('@mail', '@mail'), ('num', 'num'), ('gmail', 'gmail')], max_length=20, verbose_name='տեսակ'),
        ),
    ]
