# Generated by Django 3.1.4 on 2021-09-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210918_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_contact',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='data_contact',
            name='mail',
        ),
    ]
